baseURL: "https://kneeclass03.github.io/hugo-website/" 
title: Niklas Paul
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Blog
          url: blog/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Archive
          url: archive/
          weight: 7

params:
    description: "I am a student of Computer Science, enrolled at the Ulm University of Applied Sciences. I have worked as a research intern at both the University of Toronto and the Fraunhofer Institute for Integrated Circuits in Nuremberg."
    author: Niklas Paul
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["blog","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Niklas Paul
          subtitle: "I am a student of Computer Science, enrolled at the Ulm University of Applied Sciences. I have worked as a research intern at both the University of Toronto and the Fraunhofer Institute for Integrated Circuits in Nuremberg."
          imageUrl: "picture.jpeg"
          imageWidth: 240
          imageHeight: 240
          imageTitle: Niklas Paul - profile picture
          buttons:
            - name: Blog
              url: blog/
            - name: Projects
              url: projects/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:niklas.paul@murena.io
        - name: GitHub
          url: https://github.com/kneeclass03

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Niklas Paul"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2